name: CI

on: [ workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    services:
#       selenium-hub:
#          image: selenium/hub:3.141.59
#          ports:
#            - 4444:4444

#       chrome:
#           image: selenium/node-chrome:3.141.59
#           env:
#            HUB_HOST: selenium-hub
#            HUB_PORT: 4444

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
 
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line scrip
        run: |
           curl -X GET "http://vmrndapigwcloud:8080/api/v1/ca3s-dev-suite-handler/launch?filter.has.attributeKey=parallel_group&filter.has.attributeValue=762b47f0-75b6-4c40-a9bd-2804ecc9e408&access_token=44f88149-83ab-4026-a880-e8bcc3e79f7d" -H  "accept:application/json" -H  "Authorization:bearer 44f88149-83ab-4026-a880-e8bcc3e79f7d" > ./before.json
           curl -X GET "http://vmrndapigwcloud:8080/api/v1/ca3s-dev-suite-handler/launch?filter.has.attributeKey=parallel_group&filter.has.attributeValue=c5379996-092b-4f05-b52a-3b0ec97b1483&access_token=44f88149-83ab-4026-a880-e8bcc3e79f7d" -H  "accept:application/json" -H  "Authorization:bearer 44f88149-83ab-4026-a880-e8bcc3e79f7d" > ./after.json
   
           tests_before_upgrade=`jq '.statistics.executions.total' before.json`
           passed_test_before_upgrade=`jq '.statistics.executions.passed' before.json`
           failed_test_before_upgrade=`jq '.statistics.executions.failed' before.json`
           skipped_test_before_upgrade=`jq '.statistics.executions.skipped' before.json`
            
           tests_after_upgrade=`jq '.statistics.executions.total' after.json`
           passed_test_after_upgrade=`jq '.statistics.executions.passed' after.json`
           failed_test_after_upgrade=`jq '.statistics.executions.failed' after.json`
           skipped_test_after_upgrade=`jq '.statistics.executions.skipped' after.json`
           echo " $tests_before_upgrade"
           echo " $passed_test_before_upgrade"
           echo " $failed_test_before_upgrade"
           echo " $skipped_test_before_upgrade"
           echo " $tests_after_upgrade"
           echo " $passed_test_after_upgrade"
           echo " $failed_test_after_upgrade"
           echo " $skipped_test_after_upgrade"           
           
