name: CI

on: [ workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#    services:
#       selenium-hub:
#          image: selenium/hub:3.141.59
#          ports:
#            - 4444:4444

#       chrome:
#           image: selenium/node-chrome:3.141.59
#           env:
#            HUB_HOST: selenium-hub
#            HUB_PORT: 4444

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        id: var
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          UUID=$(uuidgen)
          echo $UUID
          echo "PR_TITLE=$UUID" >> $GITHUB_ENV
          
      - name: run
        run:
         echo ${{steps.var.outputs.UUID}}
         echo ${{env.PR_TITLE}}
     
      - name: Create network
        run: docker network create grid 
        
      - name: Download selenium
        run: docker run -d -p 4442-4444:4442-4444  --name selenium-hub selenium/hub:4.8.0-20230202
        
        
      - name:  Running
        run: docker run -d  -e SE_EVENT_BUS_HOST=selenium-hub  --shm-size="2g" -e SE_EVENT_BUS_PUBLISH_PORT=4442  -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443  selenium/node-chrome:4.8.0-20230202

#      - name: docker
#        run: docker run -d hello-world
        
      - name: Checking selenium
        if: always()
        run: |
          curl -XGET http://localhost:4444/wd/hub/status  
          
      - name: Checking selenium
        if: always()
        run: |
          curl -XGET http://localhost:4443/wd/hub/status
          
      - name: Checking selenium
        if: always()
        run: |
          curl -XGET http://localhost:4442/wd/hub/status
                  
    
